create table aluno (pk_aluno int4 generated by default as identity, altura float8, idade int4, nome varchar(255), peso float8, sexo varchar(255), user_id int4, primary key (pk_aluno));
create table exercicio (id int4 generated by default as identity, nome varchar(255), grupo_muscular_id int4, primary key (id));
create table ficha (pk_aluno int4 not null, primary key (pk_aluno));
create table grupo_muscular (id int4 generated by default as identity, nome varchar(255), primary key (id));
create table montagem_treino (carga varchar(255), divisao_treino int4, obs varchar(255), reps varchar(255), serie varchar(255), exercicio_id int4 not null, ficha_id int4 not null, primary key (exercicio_id, ficha_id));
create table perfis (user_id int4 not null, perfis int4);
create table professor (id int4 generated by default as identity, idade int4, nome varchar(255), sexo varchar(255), user_id int4, primary key (id));
create table user (id int4 generated by default as identity, email varchar(255), senha varchar(255), primary key (id));
alter table if exists aluno add constraint FKpmt3vhx13olydgexg6oktyy80 foreign key (user_id) references user;
alter table if exists exercicio add constraint FK3k13kaejua5umef307h39g6ym foreign key (grupo_muscular_id) references grupo_muscular;
alter table if exists ficha add constraint FKqi0yncvuvx0hsqx900eg67iaa foreign key (pk_aluno) references aluno;
alter table if exists montagem_treino add constraint FK2j2nej7vrtkbs2noror4srtyd foreign key (exercicio_id) references exercicio;
alter table if exists montagem_treino add constraint FK5bep1edd650w2ef1915ri3rho foreign key (ficha_id) references ficha;
alter table if exists perfis add constraint FK2qm6xlefbc3hpirg5oquis5j5 foreign key (user_id) references user;
alter table if exists professor add constraint FKi3fadgur6r833b0j7u257r0s4 foreign key (user_id) references user;
create table aluno (pk_aluno int4 generated by default as identity, altura float8, idade int4, nome varchar(255), peso float8, sexo varchar(255), user_id int4, primary key (pk_aluno));
create table exercicio (id int4 generated by default as identity, nome varchar(255), grupo_muscular_id int4, primary key (id));
create table ficha (pk_aluno int4 not null, primary key (pk_aluno));
create table grupo_muscular (id int4 generated by default as identity, nome varchar(255), primary key (id));
create table montagem_treino (carga varchar(255), divisao_treino int4, obs varchar(255), reps varchar(255), serie varchar(255), exercicio_id int4 not null, ficha_id int4 not null, primary key (exercicio_id, ficha_id));
create table perfis (user_id int4 not null, perfis int4);
create table professor (id int4 generated by default as identity, idade int4, nome varchar(255), sexo varchar(255), user_id int4, primary key (id));
create table user (id int4 generated by default as identity, email varchar(255), senha varchar(255), primary key (id));
alter table if exists aluno add constraint FKpmt3vhx13olydgexg6oktyy80 foreign key (user_id) references user;
alter table if exists exercicio add constraint FK3k13kaejua5umef307h39g6ym foreign key (grupo_muscular_id) references grupo_muscular;
alter table if exists ficha add constraint FKqi0yncvuvx0hsqx900eg67iaa foreign key (pk_aluno) references aluno;
alter table if exists montagem_treino add constraint FK2j2nej7vrtkbs2noror4srtyd foreign key (exercicio_id) references exercicio;
alter table if exists montagem_treino add constraint FK5bep1edd650w2ef1915ri3rho foreign key (ficha_id) references ficha;
alter table if exists perfis add constraint FK2qm6xlefbc3hpirg5oquis5j5 foreign key (user_id) references user;
alter table if exists professor add constraint FKi3fadgur6r833b0j7u257r0s4 foreign key (user_id) references user;
create table aluno (pk_aluno int4 generated by default as identity, altura float8, idade int4, nome varchar(255), peso float8, sexo varchar(255), user_id int4, primary key (pk_aluno))
create table exercicio (id int4 generated by default as identity, nome varchar(255), grupo_muscular_id int4, primary key (id))
create table ficha (pk_aluno int4 not null, primary key (pk_aluno))
create table grupo_muscular (id int4 generated by default as identity, nome varchar(255), primary key (id))
create table montagem_treino (carga varchar(255), divisao_treino int4, obs varchar(255), reps varchar(255), serie varchar(255), exercicio_id int4 not null, ficha_id int4 not null, primary key (exercicio_id, ficha_id))
create table perfis (user_id int4 not null, perfis int4)
create table professor (id int4 generated by default as identity, idade int4, nome varchar(255), sexo varchar(255), user_id int4, primary key (id))
create table user (id int4 generated by default as identity, email varchar(255), senha varchar(255), primary key (id))
alter table if exists aluno add constraint FKpmt3vhx13olydgexg6oktyy80 foreign key (user_id) references user
alter table if exists exercicio add constraint FK3k13kaejua5umef307h39g6ym foreign key (grupo_muscular_id) references grupo_muscular
alter table if exists ficha add constraint FKqi0yncvuvx0hsqx900eg67iaa foreign key (pk_aluno) references aluno
alter table if exists montagem_treino add constraint FK2j2nej7vrtkbs2noror4srtyd foreign key (exercicio_id) references exercicio
alter table if exists montagem_treino add constraint FK5bep1edd650w2ef1915ri3rho foreign key (ficha_id) references ficha
alter table if exists perfis add constraint FK2qm6xlefbc3hpirg5oquis5j5 foreign key (user_id) references user
alter table if exists professor add constraint FKi3fadgur6r833b0j7u257r0s4 foreign key (user_id) references user
create table aluno (pk_aluno int4 generated by default as identity, altura float8, idade int4, nome varchar(255), peso float8, sexo varchar(255), user_id int4, primary key (pk_aluno))
create table exercicio (id int4 generated by default as identity, nome varchar(255), grupo_muscular_id int4, primary key (id))
create table ficha (pk_aluno int4 not null, primary key (pk_aluno))
create table grupo_muscular (id int4 generated by default as identity, nome varchar(255), primary key (id))
create table montagem_treino (carga varchar(255), divisao_treino int4, obs varchar(255), reps varchar(255), serie varchar(255), exercicio_id int4 not null, ficha_id int4 not null, primary key (exercicio_id, ficha_id))
create table perfis (user_id int4 not null, perfis int4)
create table professor (id int4 generated by default as identity, idade int4, nome varchar(255), sexo varchar(255), user_id int4, primary key (id))
create table user (id int4 generated by default as identity, email varchar(255), senha varchar(255), primary key (id))
alter table if exists aluno add constraint FKpmt3vhx13olydgexg6oktyy80 foreign key (user_id) references user
alter table if exists exercicio add constraint FK3k13kaejua5umef307h39g6ym foreign key (grupo_muscular_id) references grupo_muscular
alter table if exists ficha add constraint FKqi0yncvuvx0hsqx900eg67iaa foreign key (pk_aluno) references aluno
alter table if exists montagem_treino add constraint FK2j2nej7vrtkbs2noror4srtyd foreign key (exercicio_id) references exercicio
alter table if exists montagem_treino add constraint FK5bep1edd650w2ef1915ri3rho foreign key (ficha_id) references ficha
alter table if exists perfis add constraint FK2qm6xlefbc3hpirg5oquis5j5 foreign key (user_id) references user
alter table if exists professor add constraint FKi3fadgur6r833b0j7u257r0s4 foreign key (user_id) references user
create table aluno (pk_aluno int4 generated by default as identity, altura float8, idade int4, nome varchar(255), peso float8, sexo varchar(255), user_id int4, primary key (pk_aluno))
create table exercicio (id int4 generated by default as identity, nome varchar(255), grupo_muscular_id int4, primary key (id))
create table ficha (pk_aluno int4 not null, primary key (pk_aluno))
create table grupo_muscular (id int4 generated by default as identity, nome varchar(255), primary key (id))
create table montagem_treino (carga varchar(255), divisao_treino int4, obs varchar(255), reps varchar(255), serie varchar(255), exercicio_id int4 not null, ficha_id int4 not null, primary key (exercicio_id, ficha_id))
create table perfis (user_id int4 not null, perfis int4)
create table professor (id int4 generated by default as identity, idade int4, nome varchar(255), sexo varchar(255), user_id int4, primary key (id))
create table user (id int4 generated by default as identity, email varchar(255), senha varchar(255), primary key (id))
alter table if exists aluno add constraint FKpmt3vhx13olydgexg6oktyy80 foreign key (user_id) references user
alter table if exists exercicio add constraint FK3k13kaejua5umef307h39g6ym foreign key (grupo_muscular_id) references grupo_muscular
alter table if exists ficha add constraint FKqi0yncvuvx0hsqx900eg67iaa foreign key (pk_aluno) references aluno
alter table if exists montagem_treino add constraint FK2j2nej7vrtkbs2noror4srtyd foreign key (exercicio_id) references exercicio
alter table if exists montagem_treino add constraint FK5bep1edd650w2ef1915ri3rho foreign key (ficha_id) references ficha
alter table if exists perfis add constraint FK2qm6xlefbc3hpirg5oquis5j5 foreign key (user_id) references user
alter table if exists professor add constraint FKi3fadgur6r833b0j7u257r0s4 foreign key (user_id) references user
